workspace:
  base: /srv/app
  path: src/github.com/webhippie/homebrew-webhippie

branches:
  - master

pipeline:
  test-formula:
    image: webhippie/ruby:latest
    pull: true
    commands:
      - rake test

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      events: [ push, tag ]
      status: [ changed, failure ]
