---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: webhippie/ruby:latest
  pull: always
  commands:
  - rake test

- name: notify
  image: plugins/matrix:latest
  pull: always
  settings:
    homeserver: https://matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    ref:
    - refs/heads/master
    - refs/tags/**
    status:
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

...
