---
# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json
AllCops:
  SuggestExtensions: false
  NewCops: enable

Naming/FileName:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - double_quotes
    - single_quotes

...
